ARQSI_IT2/ARQSI_IT2/Controllers/ImovelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ARQSI_IT2.ClassLibrary.Models;
using System.Web.UI;

using ARQSI_IT2.ClassLibrary.Models;
using ClassLibrary;

namespace ARQSI_IT2.Controllers
{
    public class ImovelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //AnuncioDBContext dbb = new AnuncioDBContext();

        // GET: Imovels
        public ActionResult Index()
        {
            var Imoveis = db.Imovels.Include(c => c.tipoimovel).Include(c => c.localização).Include(c => c.fotos);
            return View(Imoveis.ToList());
        }

        private void PopularTipoImovelDropDownList(object tiposeleccionado = null)
        {
            var tipoimovelQuery = from t in db.TipoImovels
                                  orderby t.tipo
                                  select t;

            ViewBag.Tipo_ImovelID = new SelectList(tipoimovelQuery, "ID", "TIPO", tiposeleccionado);
        }

        // GET: Imovels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Imovel imovel = db.Imovels.Find(id);
            if (imovel == null)
            {
                return HttpNotFound();
            }
            return View(imovel);
        }

        // GET: Imovels/Create
        public ActionResult Create()
        {
           
            PopularTipoImovelDropDownList();
            return View();
        }

        // POST: Imovels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,area,tipo_imovelID,morada,coordenadas,fotos")] Imovel imovel)
        {
            if (ModelState.IsValid)
            {

                //cria um objecto do tipo localização com os valores das textbox e grava no imovel
                Localização local = new Localização() { morada = Request["txtmorada"].ToString(), coordenadas = Request["txtcoordenadas"].ToString() };

                db.Localização.Add(local);

                imovel.localização = local;

                //int x = ViewBag.Tipo_ImovelID.SelectedValue;
                //imovel.tipo_imovelID = ViewBag.Tipo_ImovelID.SelectedValue;

                db.Imovels.Add(imovel);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

                
                PopularTipoImovelDropDownList(imovel.tipo_imovelID);
           
            
            return View(imovel);
        }

        // GET: Imovels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Imovel imovel = db.Imovels.Find(id);
            if (imovel == null)
            {
                return HttpNotFound();
            }
            PopularTipoImovelDropDownList(imovel.tipo_imovelID);
            return View(imovel);
        }

        // POST: Imovels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,area,tipo_imovelID,morada,coordenadas,fotos")] Imovel imovel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(imovel).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            PopularTipoImovelDropDownList(imovel.tipo_imovelID);
            return View(imovel);
        }

        // GET: Imovels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Imovel imovel = db.Imovels.Find(id);
            if (imovel == null)
            {
                return HttpNotFound();
            }
            return View(imovel);
        }

        // POST: Imovels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Imovel imovel = db.Imovels.Find(id);
            db.Imovels.Remove(imovel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ARQSI_IT2/ARQSI_IT2/Controllers/TipoImovelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ARQSI_IT2.ClassLibrary.Models;
using ARQSI_IT2.ClassLibrary.Models;
using ClassLibrary;

namespace ARQSI_IT2.Controllers
{
    public class TipoImovelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TipoImovels
        public ActionResult Index()
        {
            return View(db.TipoImovels.ToList());
        }

        // GET: TipoImovels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoImovel tipoImovel = db.TipoImovels.Find(id);
            if (tipoImovel == null)
            {
                return HttpNotFound();
            }
            return View(tipoImovel);
        }

        // GET: TipoImovels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoImovels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,tipo")] TipoImovel tipoImovel)
        {
            if (ModelState.IsValid)
            {
                db.TipoImovels.Add(tipoImovel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoImovel);
        }

        // GET: TipoImovels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoImovel tipoImovel = db.TipoImovels.Find(id);
            if (tipoImovel == null)
            {
                return HttpNotFound();
            }
            return View(tipoImovel);
        }

        // POST: TipoImovels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,tipo")] TipoImovel tipoImovel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoImovel).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoImovel);
        }

        // GET: TipoImovels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoImovel tipoImovel = db.TipoImovels.Find(id);
            if (tipoImovel == null)
            {
                return HttpNotFound();
            }
            return View(tipoImovel);
        }

        // POST: TipoImovels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoImovel tipoImovel = db.TipoImovels.Find(id);
            db.TipoImovels.Remove(tipoImovel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ARQSI_IT2/ARQSI_IT2/Views/Imovels/Create.cshtml
@model ARQSI_IT2.ClassLibrary.Models.Imovel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Imovel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Tipo_ImovelID">TipoImovel</label>
            <div class="col-md-2">
                @Html.DropDownList("Tipo_ImovelID", String.Empty)
                @Html.ValidationMessageFor(model => model.tipoimovel)
                
                </div>
            <div class="col-md-2">
               
                @Html.ActionLink("Novo Tipo de Imovel", "Create","TipoImovels")
            </div>
        </div>
        
        <br /><br />
       
       
            <div class="form-group">
                            
                <label for="txtmorada" class="control-label col-md-2">Morada   </label>
                @Html.TextBox("txtmorada")
         
              </div>
   
        <div class="form-group" >
            
            <label for="txtcoordenadas" class="control-label col-md-2">Coordenadas</label>
            <div class="col-md-10">
                @Html.TextBox("txtcoordenadas")
            </div>
        </div>
        
         
        <div class="form-group">
            @Html.LabelFor(model => model.fotos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fotos.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fotos.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ARQSI_IT2/ARQSI_IT2/Views/Imovels/Delete.cshtml
@model ARQSI_IT2.ClassLibrary.Models.Imovel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Imovel</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.area)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ARQSI_IT2/ARQSI_IT2/Views/Imovels/Details.cshtml
@model ARQSI_IT2.ClassLibrary.Models.Imovel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Imovel</h4>
    <hr />
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.tipoimovel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.tipoimovel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.area)
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.fotos.url)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.fotos.url)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.localização)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.localização.morada)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.localização.morada)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.localização.coordenadas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.localização.coordenadas)
        </dd>
       

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ARQSI_IT2/ARQSI_IT2/Views/Imovels/Edit.cshtml
@model ARQSI_IT2.ClassLibrary.Models.Imovel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Imovel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Tipo_ImovelID">TipoImovel</label>
            <div class="col-md-2">
                @Html.DropDownList("Tipo_ImovelID", String.Empty)
                @Html.ValidationMessageFor(model => model.tipoimovel)
            </div>
        </div>
        <br /><br /><br />
        @*<div class="form-group">
                @Html.LabelFor(model => model.localização.morada, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.localização.morada, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.localização.morada, "", new { @class = "text-danger" })
                </div>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.localização.coordenadas, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.localização.coordenadas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.localização.coordenadas, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <blockquote>
            <div class="control-group">
                @Html.Label("Morada")
                @Html.TextBox("txtmorada")
            </div>
            <div class="control-group">
                @Html.Label("Coordenadas")
                @Html.TextBox("txtcoordenadas")
            </div>
        </blockquote>
        <div class="form-group">
            @Html.LabelFor(model => model.fotos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fotos.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fotos.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ARQSI_IT2/ARQSI_IT2/Views/Imovels/Index.cshtml
@model IEnumerable<ARQSI_IT2.ClassLibrary.Models.Imovel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipoimovel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.localização.morada)
        </th>
        <th>
        @Html.DisplayNameFor(model => model.localização.coordenadas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fotos.url)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.area)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tipo_imovelID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.localização.morada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.localização.coordenadas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fotos.url)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>